version: '3.9'

#docker network create kong-net
networks:
  kong-net:

services:
  kong-db:
    container_name: kong-database
    image: postgres:9.6
    ports:
      - "5432:5432"
    networks:
      - kong-net      
    environment:
      - POSTGRES_PASSWORD=kong
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always  

    # docker run --rm 
    # kong migrations bootstrap

  kong-bootstrap:
    image: kong
    depends_on: 
      - kong-db
    networks:
      - kong-net
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PASSWORD=kong
    restart: always


  kong-api:
    container_name: kong
    image: kong
    depends_on: 
      - kong-db
    #links:
    #  - kong-db
    networks:
      - kong-net
    ports:
      - "8000:8000"
      - "8001:8001"
#      - "8443:8443"
#      - "8444:8444"
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PASSWORD=kong
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    restart: always

volumes:
  pgdata: {}